name: Build for Windows on Ubuntu with Threads CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: |
       sudo apt update
       sudo apt install git wine binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64
       mkdir -p ~/.wine/prefix/win64
       winecfg /v win10
    - name: configure
      run: ./configure --target=windows --enable-threads
    - name: make
      run: make
