name: Build Ubuntu with Threads CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: sudo apt update
           sudo apt install git
    - name: configure
      run: ./configure --enable-threads
    - name: make
      run: make
